### ISSUE TITLE
How to compile ? noob guide anywhere?

### ISSUE THREAD

**Issue by noxturno** [AvilanceLtd/StarryboundServer#59]
been searching the web for abit now and I find alot of info on this but not sure what I am looking for.

I want to compile this so I can try it on my server, running a debian 7

**Comment by majorcyto** [comment]
Hello, i use Ubuntu linux and you need to make sure you have mono installed. I don't bother compiling the build anymore because the new Atlassian build server does it all for you with the latest commits.

You can get the latest artifact here -> 
https://avilance.atlassian.net/builds/browse/STAR-MAS-8/artifact

Just download the exe and make sure to read this small simple guide here for linux -> 
https://github.com/AvilanceLtd/StarryboundServer/wiki/Linux-Setup

Im using that build right now on my server, and it is working great! Also some dependents are required which are not in the build server though.. i had them from before when he used to release a .zip... 

I might come back to this comment in a big and upload the dependents but i have a massive headache right now (sorry)

**Comment by noxturno** [comment]
thanks for the help !! for now I will use the first link :) still would be nice if I could know how to compile. but for now this will do !!!

**Comment by noxturno** [comment]
any idea why I get this error ? thanks in advance.

http://pastebin.com/AvqjW4vh

**Comment by majorcyto** [comment]
Uhh actually im not sure unless it's releated to you missing some of the requirements in the directory. Do you have these files as well?

```
SystemNumerics.dll
Newtonsoft.Json.dll
Mono.Posix.dll
Ionic.Zlib.dll
```

It won't work correctly without those .dll references.

**Comment by noxturno** [comment]
I followed the guide and installed it all if I am missing anything how would I fix it ?
