### ISSUE TITLE
Error while trying to run the server Debian7

### ISSUE THREAD

**Issue by noxturno** [AvilanceLtd/StarryboundServer#67]
hello I got this error after following the guide on the wiki . anyway to fix this ? I would like to run this to setup my server (vanilla atm)
http://pastebin.com/AvqjW4vh

PS: where can some one donate to this author ?

**Comment by Crashdoom** [comment]
Hey, you seem to be missing the library files that Starrybound needs to run.

Since we're not distributing the entire package anymore with them provided you'll need to get them from the following locations:
- Ionic.Zlib.dll from the DotNetZipLib-DevKit-v1.9.zip available at http://dotnetzip.codeplex.com/releases/view/68268 (Found in the zlib-v.19 folder)
- Mono.Posix.dll available at http://go-mono.com (Found in the lib/mono/4.0 installation directory: C:\Program Files (x86)\Mono-3.2.3\lib\mono\4.0)
- Newtonsoft.Json.dll from the Json50r8.zip available at http://json.codeplex.com/ (Found in the Bin/Net40 directory)
  Or you can grab them from our GitHub at https://github.com/AvilanceLtd/StarryboundServer/tree/master/Libs.

Those will need to be put in the same directory as the starbound_server.exe and the starrybound_server.exe :)

---

We're also accepting donations via [Paypal](https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=335TMEGA6XRL4&lc=GB&item_name=Avilance%20Ltd%20%3a%3a%20Starrybound%20Server&item_number=STARRY&no_note=1&no_shipping=1&currency_code=GBP&bn=PP%2dDonationsBF%3abtn_donateCC_LG%2egif%3aNonHosted) :+1:

**Comment by noxturno** [comment]
thanks man I will be droping a donation soon !!!!!, just finally manage to run this on my server, btw there is a person on server with space between his name, how can I promote that person? his name is "Iron Hand"

**Comment by Crashdoom** [comment]
If someone has a space you can use quotations to target them, so if their name is Joe Bloggs, then you can use /group adduser "Joe Bloggs" player for example :P

**Comment by noxturno** [comment]
So everything worked fine, but after a server crashed everything went back to default, even me after doing /auth code to gain admin , now I am no longer admin and my config file keeps going back to default, also if I wanted to stop the server what command do I do ? besides closing the screen session ?

**Comment by Crashdoom** [comment]
The command to shutdown the server is /shutdown, you can restart it using /restart. I'm going to close this issue since it was fixed, however the new issue you're having is not - See issue #69
