### ISSUE TITLE
Version mismatch causes crash on load

### ISSUE THREAD

**Issue by Sebron** [AvilanceLtd/StarryboundServer#77]
Starbound servers have been updated to version 639, starrybound is expecting 636. This causes a version mismatch which causes Starrybound to terminate. This occurs on M9 as well as D19 builds.

**Comment by noxturno** [comment]
I am sure he will update when he gets a chance.

**Comment by Paragon321** [comment]
In StarryboundServer.cs Line 38 should read:
        public static readonly int ProtocolVersion = 639;
rather than 636 as it does currently... assuming the data packets haven't been modified in this version, that should be enough to get it working... I tried it myself, and was able to get the server up and running... but I continuously get invalid password problems attempting to log in... not sure if it is related or not.

**Comment by Symple85** [comment]
I changed the ProtocolVersion and the server is up and running, I just get this error when trying to connect.
Warn: I/O error from 127.0.0.1:55816 in NetSocket read loop or device closed: EofException: Error, unexpected end of file found 1 1 1
Starrybound log file:
http://pastebin.com/k2ZPka4p
Starbound Server Log file:
http://pastebin.com/a63BwjwM

**Comment by Sebron** [comment]
Issue fixed with update to M10. Successful server launch v1.3.039743 (639)
